### ISSUE TITLE
Just doesn't show

### ISSUE THREAD

**Issue by stefanwalther** [Vektah/CodeGlance#108]
Hi,

I am trying to activate Code Glance for WebStorm now for ages ;-)
Currently I am using the latest version of WebStorm (11.0.2) and just updated Code Glance, but it never shows ... Am I missing something. What do I have to do, to get it active?

Thx a lot!
Regards
Stefan

**Comment by zeljic** [comment]
Hi, it's probably related to #102

**Comment by zeljic** [comment]
Check your plugin version, 1.4.4. version fixes the issue.

**Comment by Vektah** [comment]
This could also be related to https://github.com/Vektah/CodeGlance/issues/106

There was a broken release that went out to ~60 people, the steps listed there should fix it.

**Comment by stefanwalther** [comment]
Hi, I have version 1.4.4 installed, but still doesn't work. Just uninstalled and re-installed again, still nothing shows up. Maybe related to Windows?

**Comment by Vektah** [comment]
Can you try doing this?
 - Close Intellij
 - Go to C:\Users\\\<User>\\\.IntelliJIdea15\config\plugins
 - delete all the CodeGlance things from here (jars, zips, folders)
 - reinstall the plugin from the repo (which should now be fixed)

**Comment by BonBonSlick** [comment]
Something went wrong. The issue occurred for me after some time, it disappeared and does not show again. Cleared plugin folder, reinstalled, does not work. Or maybe there is "enable" button somewhere?
PHPstorm 2019.3

**Comment by wesleymusgrove** [comment]
@BonBonSlick this happened to me too very recently within the past two weeks or so.  The minimap just disappeared.  I have uninstalled and reinstalled the plugin to no avail. I'm running PHPStorm 2019.3.1

![image](https://user-images.githubusercontent.com/1711791/72457446-3d342c80-378c-11ea-93a3-2a33f2a192c0.png)

**Comment by rcosta9** [comment]
I am having the exact same issue. PHPStorm 2019.3.3 (according to the IntelliJ toolbox).

**Comment by stefan-reloyalty** [comment]
Well, It appears all you have to do is press Ctrl+Shift+G - this is the key combination to toggle the minimap on/off. Why it hides after IDE update? I don't know, but many people have this issue, including me.

**Comment by AndreKR** [comment]
> It appears all you have to do is press Ctrl+Shift+G

What is that a shortcut for? I found nothing, neither in View nor in Tools nor in Code (you know, because *Code*Glance).

**Comment by nihadelekberzade** [comment]
> Well, It appears all you have to do is press Ctrl+Shift+G - this is the key combination to toggle the minimap on/off. Why it hides after IDE update? I don't know, but many people have this issue, including me.

You are life saver man. Respect++

**Comment by AndrewStarkov** [comment]
still hidded, macbook pro 2019, shift + cmd + g does not help

**Comment by javiddeveloper** [comment]
Pressing **ctrl + shift + g** toggles the CodeGlance plug-in

**Comment by Mizar01** [comment]
CTRL + SHIFT + G saved me hours!

**Comment by Heiland** [comment]
in my case the option 'Disabled by default' was activated, which hides the minimap:
![Image](https://github.com/user-attachments/assets/097642f7-d478-47af-a877-28f3abf0c892)

also, the shortcut ctrl+shift+g only works using the keymap from Visual Studio. it does not work using IntelliJ keymap.
